# Generated by Django 2.2.11 on 2020-06-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_remove_choosecourse_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choosecourse',
            name='ocid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_course', to='teacher.OfferCourse'),
        ),
        migrations.AlterField(
            model_name='choosecourse',
            name='sid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choose_course', to='student.Student'),
        ),
    ]
